SET FEEDBACK OFF
SET HEADING ON
SET MARKUP CSV ON QUOTE ON
SET PAGESIZE 0
SET TRIMSPOOL ON
SET LINESIZE 32767

SELECT 'AUX_CLIENTE' AS ENTITY, COUNT(*) AS RECORDS FROM SYSTEM.AUX_CLIENTE WHERE RUC IS NOT NULL AND TRIM(RUC) IS NOT NULL
UNION ALL
SELECT 'AUX_VENTASFAMP', COUNT(*) FROM SYSTEM.AUX_VENTASFAMP WHERE RUC IS NOT NULL AND TRIM(RUC) IS NOT NULL
UNION ALL
SELECT 'AUX_SALDO_CLIENTE', COUNT(*) FROM SYSTEM.AUX_SALDO_CLIENTE WHERE RUC IS NOT NULL AND TRIM(RUC) IS NOT NULL
UNION ALL
SELECT 'CLI_DIRECCION', COUNT(*) FROM SYSTEM.CLI_DIRECCION WHERE CLTE_IDCLIENTE IS NOT NULL
UNION ALL
SELECT 'AUX_INVENTARIO', COUNT(*) FROM SYSTEM.AUX_INVENTARIO WHERE ARTL_ARTICULO IS NOT NULL AND TRIM(ARTL_ARTICULO) IS NOT NULL
UNION ALL
SELECT 'VEN_PRECDESC', COUNT(*) FROM SYSTEM.VEN_PRECDESC WHERE ARTL_ARTICULO IS NOT NULL AND TRIM(ARTL_ARTICULO) IS NOT NULL
UNION ALL
SELECT 'DWH_VENTAS', COUNT(*) FROM SYSTEM.DWH_VENTAS WHERE ARTL_ARTICULO IS NOT NULL
UNION ALL
SELECT 'VEN_VENTAS', COUNT(*) FROM SYSTEM.VEN_VENTAS WHERE NUMERO IS NOT NULL
UNION ALL
SELECT 'VEN_DETAPROD', COUNT(*) FROM SYSTEM.VEN_DETAPROD WHERE VNTA_NUMERO IS NOT NULL
UNION ALL
SELECT 'ALM_DETALOTE', COUNT(*) FROM SYSTEM.ALM_DETALOTE WHERE NUMLOTE IS NOT NULL
UNION ALL
SELECT 'GEN_TMPPROVEEDOR', COUNT(*) FROM SYSTEM.GEN_TMPPROVEEDOR WHERE RUC IS NOT NULL AND TRIM(RUC) IS NOT NULL
UNION ALL
SELECT 'COM_TMPCOMPRAS', COUNT(*) FROM SYSTEM.COM_TMPCOMPRAS WHERE PROV_CODIGO IS NOT NULL
ORDER BY 1;

EXIT;