set pagesize 0 feedback off verify off heading on echo off termout off
set trimspool on linesize 32767
set markup csv on quote on

SELECT 'AUX_CLIENTE' as TABLA, COUNT(*) as REGS FROM SYSTEM.AUX_CLIENTE WHERE RUC IS NOT NULL;
SELECT 'AUX_VENTASFAMP' as TABLA, COUNT(*) as REGS FROM SYSTEM.AUX_VENTASFAMP WHERE RUC IS NOT NULL;
SELECT 'AUX_SALDO_CLIENTE' as TABLA, COUNT(*) as REGS FROM SYSTEM.AUX_SALDO_CLIENTE WHERE RUC IS NOT NULL;
SELECT 'CLI_DIRECCION' as TABLA, COUNT(*) as REGS FROM SYSTEM.CLI_DIRECCION WHERE CLTE_IDCLIENTE IS NOT NULL;
SELECT 'AUX_INVENTARIO' as TABLA, COUNT(*) as REGS FROM SYSTEM.AUX_INVENTARIO WHERE ARTL_ARTICULO IS NOT NULL;
SELECT 'VEN_PRECDESC' as TABLA, COUNT(*) as REGS FROM SYSTEM.VEN_PRECDESC WHERE ARTL_ARTICULO IS NOT NULL;
SELECT 'DWH_VENTAS' as TABLA, COUNT(*) as REGS FROM SYSTEM.DWH_VENTAS WHERE ARTL_ARTICULO IS NOT NULL;
SELECT 'VEN_VENTAS' as TABLA, COUNT(*) as REGS FROM SYSTEM.VEN_VENTAS WHERE NUMERO IS NOT NULL;
SELECT 'VEN_DETAPROD' as TABLA, COUNT(*) as REGS FROM SYSTEM.VEN_DETAPROD WHERE VNTA_NUMERO IS NOT NULL;
SELECT 'ALM_DETALOTE' as TABLA, COUNT(*) as REGS FROM SYSTEM.ALM_DETALOTE WHERE NUMLOTE IS NOT NULL;
SELECT 'GEN_TMPPROVEEDOR' as TABLA, COUNT(*) as REGS FROM SYSTEM.GEN_TMPPROVEEDOR WHERE RUC IS NOT NULL;
SELECT 'COM_TMPCOMPRAS' as TABLA, COUNT(*) as REGS FROM SYSTEM.COM_TMPCOMPRAS WHERE PROV_CODIGO IS NOT NULL;

exit;