import { jsPDF } from "jspdf";
const generateCapaPdf = async (record) => {
  const doc = new jsPDF(); const margin = 20;
  doc.setFontSize(18); doc.setFont("helvetica", "bold");
  doc.text("Acta de CAPA", margin, 25);
  doc.setFontSize(12); doc.setFont("helvetica", "normal");
  doc.text(`Severidad: ${record?.severity || "N/A"}`, margin, 40);
  doc.text(`Estado: ${record?.status || "open"}`, margin, 48);
  doc.text(`Fuente: ${record?.sourceType || "N/A"}`, margin, 56);
  const qrData = JSON.stringify({ id: record?.id, ts: new Date().toISOString() });
  doc.setFontSize(10); doc.setTextColor(100);
  doc.text("QR:", margin, 80);
  const qrSize = 30; doc.setFillColor(0,0,0); doc.rect(margin, 85, qrSize, qrSize, "F");
  doc.setTextColor(0); doc.setFontSize(8); doc.text("GXP", margin, qrSize + 90);
  doc.setFontSize(8); doc.setTextColor(150);
  doc.text(`Generado: ${new Date().toLocaleString()}`, margin, doc.internal.pageSize.getHeight() - 15);
  doc.text("CAPA GXP - FamSPI", margin, doc.internal.pageSize.getHeight() - 9);
  return doc;
};
const downloadCapaPdf = async (record, filename = "capa.pdf") => { const doc = await generateCapaPdf(record); doc.save(filename); };
const getCapaPdfBase64 = async (record) => { const doc = await generateCapaPdf(record); return doc.output("datauristring"); };
export default { generateCapaPdf, downloadCapaPdf, getCapaPdfBase64 };